"""Project config — proj/rulestools.toml.

Auto-generated by `rulestools detect`, read by `rulestools scan`.

File layout (TOML):
  [scan]
  languages = ["rust", "slint"]

  [ignore]
  paths = ["target", "node_modules", ".git"]
"""

from __future__ import annotations
import tomllib
from dataclasses import dataclass, field
from pathlib import Path

CONFIG_PATH = Path("proj") / "rulestools.toml"   # relative to project root

# Extension → scanner name
EXT_TO_LANG: dict[str, str] = {
    ".rs":    "rust",
    ".slint": "slint",
    ".js":    "js",
    ".mjs":   "js",
    ".ts":    "js",
    ".tsx":   "js",
    ".css":   "css",
    ".scss":  "css",
    ".sass":  "css",
    ".py":    "python",
    ".kt":    "kotlin",
    ".kts":   "kotlin",
}

_DEFAULT_IGNORE = [
    "target", "node_modules", ".git", "dist", "build",
    ".cargo", "__pycache__", ".venv", "venv", ".tox",
]


@dataclass
class ScanConfig:
    languages:    list[str]
    ignore_paths: list[str] = field(default_factory=lambda: list(_DEFAULT_IGNORE))

    # ── load ────────────────────────────────────────────────────────────────

    @classmethod
    def load(cls, project_root: Path) -> "ScanConfig | None":
        config_file = project_root / CONFIG_PATH
        if not config_file.exists():
            return None
        with open(config_file, "rb") as f:
            data = tomllib.load(f)
        langs = (
            data.get("scan", {}).get("languages", [])
            or data.get("project", {}).get("languages", [])
        )
        return cls(
            languages    = langs,
            ignore_paths = data.get("ignore", {}).get("paths", list(_DEFAULT_IGNORE)),
        )

    # ── save ────────────────────────────────────────────────────────────────

    def save(self, project_root: Path) -> Path:
        config_file = project_root / CONFIG_PATH
        config_file.parent.mkdir(exist_ok=True)

        lang_items   = "\n".join(f'  "{l}",' for l in self.languages)
        ignore_items = "\n".join(f'  "{p}",' for p in self.ignore_paths)

        toml = (
            "# rulestools project config\n"
            "# Generated by: rulestools detect\n"
            "# Edit to add/remove languages or ignore paths.\n"
            "\n"
            "[scan]\n"
            "languages = [\n"
            f"{lang_items}\n"
            "]\n"
            "\n"
            "[ignore]\n"
            "paths = [\n"
            f"{ignore_items}\n"
            "]\n"
        )
        config_file.write_text(toml, encoding="utf-8")
        return config_file

    # ── detect ──────────────────────────────────────────────────────────────

    @classmethod
    def detect(cls, project_root: Path) -> "ScanConfig":
        """Walk the project tree and infer which languages are present."""
        skip = set(_DEFAULT_IGNORE)
        found: set[str] = set()

        for path in project_root.rglob("*"):
            if not path.is_file():
                continue
            if any(part in skip for part in path.parts):
                continue
            lang = EXT_TO_LANG.get(path.suffix.lower())
            if lang:
                found.add(lang)

        return cls(languages=sorted(found))
